package lt.codedicted.egzaminai.core.model.types

enum class ExamName {
    LITHUANIAN_LANGUAGE,
    INFORMATICS,
    BIOLOGY,
    MATH,
    CHEMISTRY,
    PHYSICS,
    HISTORY,
    ENGLISH_LANGUAGE,
    FRENCH_LANGUAGE,
    RUSSIAN_LANGUAGE,
    GERMAN_LANGUAGE,
    GEOGRAPHY,
    NATIVE_BELARUSIAN_LANGUAGE,
    NATIVE_POLISH_LANGUAGE,
    NATIVE_RUSSIAN_LANGUAGE,
    MUSIC_CREATIVITY_TASK,
    MUSIC_NOTES,
    MUSIC_HISTORY,
    MUSICAL_THINKING
}
